name = "modfest-skyandsea"
mc_version = "1.20.4"

[jar]
type = "fabric"
loader = "0.15.3"
installer = "latest"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true
jvm_args = "-XX:+UseZGC -XX:+ZGenerational"

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "0.92.0+1.20.4"

[[mods]]
type = "modrinth"
id = "fabric-language-kotlin"
version = "1.10.17+kotlin.1.9.22"

[[mods]]
type = "modrinth"
id = "modmenu"
version = "9.0.0"

[[mods]]
type = "url"
url = "https://jaskarth.com/pub/mods/player-roles-1.6.8.jar"

[[mods]]
type = "url"
url = "https://jaskarth.com/pub/mods/fireblanket-0.4.0.jar"

[[mods]]
type = "url"
url = "https://jaskarth.com/pub/mods/glowcase-1.2.1+1.20.4.jar"

[[mods]]
type = "modrinth"
id = "modernfix"
version = "5.10.2+mc1.20.4"

[[mods]]
type = "modrinth"
id = "spark"
version = "1.10.58-fabric"

[[mods]]
type = "modrinth"
id = "sodium"
version = "mc1.20.3-0.5.5"

[[mods]]
type = "modrinth"
id = "axiom"
version = "2.2.1"

[[mods]]
type = "modrinth"
id = "worldedit"
version = "7.2.18"

[[mods]]
type = "modrinth"
id = "emi"
version = "jXyglcrU"

[[mods]]
type = "modrinth"
id = "lithium"
version = "nMhjKWVE"

[[mods]]
type = "modrinth"
id = "indium"
version = "tD2IqHXC"

[[mods]]
type = "modrinth"
id = "badpackets"
version = "SvSHT7FN"

[[mods]]
type = "modrinth"
id = "yacl"
version = "3.3.1+1.20.4-fabric"

[[mods]]
type = "modrinth"
id = "smartbrainlib"
version = "1.13"

[[mods]]
type = "modrinth"
id = "cloth-config"
version = "13.0.121+fabric"

[[mods]]
type = "modrinth"
id = "geckolib"
version = "Z4SMiN06"

[[mods]]
type = "modrinth"
id = "trinkets"
version = "3.8.0"

[[mods]]
type = "modrinth"
id = "wthit"
version = "fabric-10.0.1"

[[mods]]
type = "modrinth"
id = "teabridge"
version = "1.2.3"

[[mods]]
type = "modrinth"
id = "simple-voice-chat"
version = "fabric-1.20.4-2.4.32"

[[mods]]
type = "modrinth"
id = "styled-nicknames"
version = "1.4.0+1.20.3"

[[mods]]
type = "modrinth"
id = "styled-sidebars"
version = "mrmtsYJL"

[[mods]]
type = "modrinth"
id = "styledplayerlist"
version = "jcLxMRaH"

[[mods]]
type = "modrinth"
id = "styled-chat"
version = "2.4.0+1.20.3"

[[mods]]
type = "modrinth"
id = "drogstyle"
version = "1.3.1+1.20.4"

[[mods]]
type = "modrinth"
id = "crunchy-crunchy-advancements"
version = "1.6.2+1.20.2"

[[mods]]
type = "modrinth"
id = "owo-lib"
version = "0.12.0+1.20.3"

[[mods]]
type = "modrinth"
id = "switchy"
version = "2.9.0+1.20.4"

[[mods]]
type = "modrinth"
id = "switchy-proxy"
version = "1.7.0+1.20.4"

[[mods]]
type = "modrinth"
id = "fabrictailor"
version = "2.3.0"

[[mods]]
type = "modrinth"
id = "ears"
version = "1.4.6+fabric-1.20.2"

[[mods]]
type = "modrinth"
id = "sidekick"
version = "jRAvZUss"

[[mods]]
type = "modrinth"
id = "blocky-bass"
version = "1oRMoeLe"

[[mods]]
type = "modrinth"
id = "starcaller"
version = "vREBSPTX"

[[mods]]
type = "modrinth"
id = "contrail"
version = "UNlU07tE"

[[mods]]
type = "modrinth"
id = "toxsky"
version = "PE1DBsz4"

[[mods]]
type = "modrinth"
id = "pet-bottle-rocket"
version = "EMNmLdWf"

[[mods]]
type = "modrinth"
id = "skybox_athome"
version = "A9YpZkm1"

[[mods]]
type = "modrinth"
id = "arctic"
version = "WWFqiy4s"

[[mods]]
type = "modrinth"
id = "seagulls"
version = "yP2sUiVD"

[[mods]]
type = "modrinth"
id = "gadgets-of-the-sky"
version = "RdHzOZKN"

[[mods]]
type = "modrinth"
id = "env.json"
version = "CBQek3jU"

[[mods]]
type = "modrinth"
id = "potatoesplus"
version = "xxvfihTT"

[[mods]]
type = "modrinth"
id = "loggerhead-luminancies"
version = "cWb8HuiP"

[[mods]]
type = "modrinth"
id = "glide-away"
version = "go1RyWf6"

[[mods]]
type = "modrinth"
id = "weathersync"
version = "KkUjGlNv"

[[mods]]
type = "modrinth"
id = "boids"
version = "iU8B8Wkw"

[[mods]]
type = "modrinth"
id = "birds-boids-addon"
version = "qQcUk86d"

[[mods]]
type = "modrinth"
id = "cerulean"
version = "p0HRA1Ep"

[[mods]]
type = "modrinth"
id = "clouded-isles"
version = "QfRJNSiE"

[[mods]]
type = "modrinth"
id = "schmarrn-fireworks"
version = "T9HJgbsq"

[[mods]]
type = "modrinth"
id = "anshar"
version = "ZX0xmM5Z"

[[mods]]
type = "modrinth"
id = "fishhead"
version = "kjkXFzU8"

[[mods]]
type = "modrinth"
id = "gods-of-olympus"
version = "ApCuzPaA"

[[mods]]
type = "modrinth"
id = "wizcraft"
version = "o9dCFuhL"

[[mods]]
type = "modrinth"
id = "perihelion"
version = "fFBFJaJ5"

[[mods]]
type = "modrinth"
id = "mutagen"
version = "hgcY7Gea"

[[mods]]
type = "modrinth"
id = "pescatore"
version = "X6Nwdhrz"

[[mods]]
type = "modrinth"
id = "env-driven-assets"
version = "iliWwvXj"

[[mods]]
type = "modrinth"
id = "pesky-seagulls"
version = "KLntrhIl"

[[mods]]
type = "modrinth"
id = "flutterandflounder"
version = "S33yyx2G"

[[mods]]
type = "modrinth"
id = "fluiwid"
version = "MX7qmMau"

[[mods]]
type = "modrinth"
id = "partnership"
version = "ZI7VHNtP"

[[mods]]
type = "modrinth"
id = "reel"
version = "BAwLBNQL"

[[mods]]
type = "modrinth"
id = "boatism"
version = "c9XfOg9n"

[[mods]]
type = "modrinth"
id = "the-skys-the-limit"
version = "ogKJHhlk"

[[mods]]
type = "modrinth"
id = "capiche"
version = "ItXNThQy"

[[mods]]
type = "modrinth"
id = "whalestrom"
version = "vc7VVtO7"

[[mods]]
type = "modrinth"
id = "glide"
version = "SSgjgT31"

[[mods]]
type = "modrinth"
id = "resurfaced"
version = "OBxLGK7I"

[[mods]]
type = "modrinth"
id = "operation-starcleave"
version = "9flzmYmU"

[[mods]]
type = "modrinth"
id = "moonrise"
version = "Dys1Pyys"

[[mods]]
type = "modrinth"
id = "rapscallions-and-rockhoppers"
version = "1.1.1-fabric"

[[mods]]
type = "modrinth"
id = "wild-magix"
version = "XaEApfFN"

[[mods]]
type = "url"
url = "https://unascribed.b-cdn.net/picturesign-2.0.0-beta.1%2Bunascribedtheora5-1.20.4.jar"
filename = "picturesign-2.0.0-beta.1+unascribedtheora5-1.20.4.jar"
desc = "PictureSign"

[[mods]]
type = "url"
url = "https://blanketcon.b-cdn.net/pub/1.20/scatteredshards-1.5.0.jar"
filename = "scatteredshards-1.5.0.jar"
desc = "Scattered Shards"

[[mods]]
type = "modrinth"
id = "demobox"
version = "8mqBSol8"

[worlds.modfest-1-20.download]
type = "ghrel"
repo = "ModFest/modfest-1-20"
tag = "base"
asset = "modfest-1-20-base-world.zip"

[markdown]
files = ["README.md"]
auto_update = false

[options]
